
CREATE TABLE IF NOT EXISTS category (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    "type" INTEGER NOT NULL DEFAULT 0,
    color CHAR(7) NOT NULL,
    icon VARCHAR(25) NOT NULL,
    parent_id INTEGER,
    FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    image TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    category_id INTEGER NOT NULL,
    is_origin BOOLEAN NOT NULL DEFAULT 0,
    FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS origin_item (
    origin_id INTEGER NOT NULL,
    item_id INTEGER NOT NULL,
    PRIMARY KEY (origin_id, item_id),
    FOREIGN KEY (origin_id) REFERENCES item(id) ON DELETE CASCADE,
    FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 0 AND 5),
    comment TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    item_id INTEGER NOT NULL,
    FOREIGN KEY (item_id) REFERENCES item(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS review_image (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    image TEXT NOT NULL,
    review_id INTEGER NOT NULL,
    FOREIGN KEY (review_id) REFERENCES review(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS category_rating (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    category_id INTEGER NOT NULL,
    FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS category_rating_value (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    "value" INTEGER NOT NULL CHECK (value BETWEEN 0 AND 10),
    review_id INTEGER NOT NULL,
    category_rating_id INTEGER NOT NULL,
    FOREIGN KEY (review_id) REFERENCES review(id) ON DELETE CASCADE,
    FOREIGN KEY (category_rating_id) REFERENCES category_rating(id) ON DELETE CASCADE
);